class ImportWorkcamp < ActiveRecord::Base

  def self.codes_sk
    { "empty": "---",
      "1": "Albánsko",
      "2": "Alžírsko",
      "3": "Argentína",
      "4": "Arménsko",
      "6": "Austrália",
      "7": "Azerbajdžan",
      "11": "Bangladéš",
      "9": "Belgicko",
      "10": "Bielorusko",
      "88": "Bolívia",
      "12": "Bosna a Hercegovina",
      "92": "Botswana",
      "99": "Brazília",
      "13": "Bulharsko",
      "8": "Burundi",
      "18": "Česká republika",
      "17": "Chorvátsko",
      "51": "Čierna Hora",
      "87": "Čile",
      "90": "Čína",
      "20": "Dánsko",
      "21": "Egypt",
      "93": "Ekvádor",
      "23": "Estónsko",
      "84": "Filipíny",
      "24": "Fínsko",
      "25": "Francúzsko",
      "100": "Ghana",
      "28": "Grécko",
      "29": "Grónsko",
      "102": "Grónsko",
      "27": "Gruzínsko",
      "30": "Guatemala",
      "54": "Holandsko",
      "85": "Honduras",
      "83": "Hong Kong",
      "34": "India",
      "33": "Indonézia",
      "35": "Írsko",
      "37": "Island",
      "38": "Izrael",
      "82": "Jamajka",
      "40": "Japonsko",
      "94": "Jordánsko",
      "14": "Kambodža",
      "16": "Kamerun",
      "15": "Kanada",
      "97": "Kazachstan",
      "41": "Keňa",
      "43": "Kirgizsko",
      "42": "Kórea",
      "98": "Kosovo",
      "91": "Kostarika",
      "95": "Lichtenštajnsko",
      "44": "Litva",
      "81": "Lotyšsko",
      "45": "Luxemburg",
      "46": "Macedónsko",
      "31": "Maďarsko",
      "49": "Malajzia",
      "96": "Malta",
      "47": "Maroko",
      "48": "Maurícius",
      "50": "Mexiko",
      "53": "Moldavsko",
      "52": "Mongolsko",
      "19": "Nemecko",
      "80": "Nepal",
      "86": "Nikaragua",
      "55": "Nórsko",
      "56": "Palestína",
      "89": "Peru",
      "57": "Poľsko",
      "58": "Portugalsko",
      "5": "Rakúsko",
      "59": "Rumunsko",
      "60": "Rusko",
      "36": "Severné Írsko",
      "61": "Škótsko",
      "65": "Slovensko",
      "62": "Slovinsko",
      "22": "Španielsko",
      "63": "Srbsko",
      "64": "Srí Lanka",
      "101": "Srí Lanka",
      "32": "Švajčiarsko",
      "66": "Švédsko",
      "68": "Tadžikistan",
      "69": "Taiwan",
      "39": "Taliansko",
      "73": "Tanzánia",
      "67": "Thajsko",
      "70": "Togo",
      "71": "Tunisko",
      "72": "Turecko",
      "74": "Uganda",
      "75": "Ukrajina",
      "76": "USA",
      "77": "Vanuatu",
      "26": "Veľká Británia",
      "78": "Vietnam"
    }
  end

  def self.codes_en
    {
      "empty": "---",
      "1": "Albania",
      "2": "Algeria",
      "3": "Argentina",
      "4": "Armenia",
      "6": "Australia",
      "5": "Austria",
      "7": "Azerbaijan",
      "11": "Bangladesh",
      "10": "Belarus",
      "9": "Belgium",
      "88": "Bolivia",
      "12": "Bosnia and Hercegovina",
      "13": "Bulgaria",
      "8": "Burundi",
      "14": "Cambodia",
      "16": "Camerun",
      "15": "Canada",
      "87": "Chile",
      "90": "China",
      "91": "Costarica",
      "17": "Croatia",
      "18": "Czech Republic",
      "20": "Denmark",
      "21": "Egypt",
      "23": "Estonia",
      "24": "Finland",
      "25": "France",
      "27": "Georgia",
      "19": "Germany",
      "26": "Great Britain",
      "28": "Greece",
      "29": "Greenland",
      "30": "Guatemala",
      "85": "Honduras",
      "83": "Hong Kong",
      "31": "Hungaria",
      "37": "Iceland",
      "34": "India",
      "33": "Indonesia",
      "35": "Ireland",
      "38": "Israel",
      "39": "Italy",
      "82": "Jamaica",
      "40": "Japan",
      "41": "Kenya",
      "43": "Kirgistan",
      "42": "Korea",
      "81": "Latvia",
      "44": "Lithuania",
      "45": "Luxemburg",
      "46": "Macedonia",
      "49": "Malaysia",
      "47": "Marocco",
      "48": "Mauritius",
      "50": "Mexico",
      "53": "Moldavia",
      "52": "Mongolia",
      "51": "Montenegro",
      "80": "Nepal",
      "54": "Netherlands",
      "86": "Nicaragua",
      "36": "North Ireland",
      "55": "Norway",
      "56": "Palestine",
      "89": "Peru",
      "84": "Philippines",
      "57": "Poland",
      "58": "Portugal",
      "59": "Romania",
      "60": "Russia",
      "61": "Scotland",
      "63": "Serbia",
      "65": "Slovakia",
      "62": "Slovenia",
      "22": "Spain",
      "64": "Sri Lanka",
      "66": "Sweden",
      "32": "Switzerland",
      "69": "Taiwan",
      "68": "Tajikistan",
      "73": "Tanzania",
      "67": "Thailand",
      "70": "Togo",
      "71": "Tunesia",
      "72": "Turkey",
      "74": "Uganda",
      "75": "Ukraine",
      "76": "United States",
      "77": "Vanuatu",
      "78": "Vietnam"
    }
  end

  def self.find_code_for_country_name(country)
    r1 = codes_sk.select{|key, one| one == country }
    r2 = codes_en.select{|key, one| one == country }
    if r1 != nil
      return r1
    else
      return r2
    end
  end
end
